"use client";
import { hindiCitizenship } from "../hindi";

import { useMemo, useState } from "react";
import { SiteNav, useLanguage } from "../language";
import { officialLists, studyCards, studyResources, type TestVersion } from "./study-data";
import "./citizenship.css";

import { useTranslations, TranslatedText, TranslationNotice } from "../translations";
import { locale, translationStatus } from "../locale";
import type { Language } from "../locale";
type Feedback = { language?: Language; verdict: "correct" | "needs-work" | "unclear"; feedback: string; hint: string; mode?: "ai" | "official" };

const copy = {
  हिन्दी: hindiCitizenship,
  English: { title:"Study for the citizenship test", intro:"Use an official question bank, a new randomized practice round, and clear feedback on your answers.", choose:"Choose your test version", before:"I filed Form N-400 before October 20, 2025", after:"I filed on or after October 20, 2025", unsure:"Not sure? Check your N-400 filing date or ask a qualified organization. This tool cannot determine your test version.", practice:"Random practice round", round:"A new round is drawn from the complete official list every time you start again.", question:"Question", answer:"Your spoken or typed answer", placeholder:"Type your answer here…", check:"Check my answer", checking:"Checking…", reveal:"Show official answers", hide:"Hide official answers", listen:"Read question aloud", next:"Next question", previous:"Previous", restart:"New randomized round", complete:"Practice round complete", progress:"Answers reviewed", official:"Official USCIS answers", englishNote:"Translations are for study and are not official. The original English text is available below.", list:"Open the complete official question list", directory:"Classes and study resources", search:"Search classes or resources", all:"All", classes:"Local classes", materials:"Official study materials", call:"Call", visit:"Open resource", none:"No matching resources.", note:"This study tool is not legal advice and does not determine eligibility. The real civics test is oral. USCIS may accept more than one answer; verify changing answers directly with USCIS." },
  Español: { title:"Estudie para el examen de ciudadanía", intro:"Use una lista oficial de preguntas, una práctica aleatoria y comentarios claros sobre sus respuestas.", choose:"Elija la versión de su examen", before:"Presenté el formulario N-400 antes del 20 de octubre de 2025", after:"Lo presenté el 20 de octubre de 2025 o después", unsure:"¿No está seguro? Revise la fecha de presentación del N-400 o consulte a una organización calificada. Esta herramienta no determina su versión.", practice:"Práctica aleatoria", round:"Cada vez se selecciona una nueva práctica de la lista oficial completa.", question:"Pregunta", answer:"Su respuesta hablada o escrita", placeholder:"Escriba su respuesta…", check:"Revisar mi respuesta", checking:"Revisando…", reveal:"Mostrar respuestas oficiales", hide:"Ocultar respuestas oficiales", listen:"Escuchar la pregunta", next:"Siguiente pregunta", previous:"Anterior", restart:"Nueva práctica aleatoria", complete:"Práctica terminada", progress:"Respuestas revisadas", official:"Respuestas oficiales de USCIS", englishNote:"Las traducciones son para estudiar y no son oficiales. El texto original en inglés está disponible abajo.", list:"Abrir lista oficial completa", directory:"Clases y recursos de estudio", search:"Buscar clases o recursos", all:"Todos", classes:"Clases locales", materials:"Materiales oficiales", call:"Llamar", visit:"Abrir recurso", none:"No hay recursos que coincidan.", note:"Esta herramienta no es asesoría legal y no determina elegibilidad. El examen real es oral. USCIS puede aceptar más de una respuesta; confirme las respuestas que cambian directamente con USCIS." },
  Русский: { title:"Подготовка к тесту на гражданство", intro:"Используйте официальный список вопросов, случайную практику и понятную обратную связь по ответам.", choose:"Выберите версию теста", before:"Я подал(а) форму N-400 до 20 октября 2025 года", after:"Я подал(а) форму 20 октября 2025 года или позже", unsure:"Не уверены? Проверьте дату подачи N-400 или спросите в квалифицированной организации. Этот инструмент не определяет вашу версию теста.", practice:"Случайная практика", round:"При каждом новом запуске выбирается новая серия из полного официального списка.", question:"Вопрос", answer:"Ваш устный или письменный ответ", placeholder:"Введите ответ…", check:"Проверить ответ", checking:"Проверяем…", reveal:"Показать официальные ответы", hide:"Скрыть официальные ответы", listen:"Прослушать вопрос", next:"Следующий вопрос", previous:"Назад", restart:"Новая случайная практика", complete:"Практика завершена", progress:"Проверено ответов", official:"Официальные ответы USCIS", englishNote:"Переводы предназначены для учёбы и не являются официальными. Английский оригинал доступен ниже.", list:"Открыть полный официальный список", directory:"Занятия и учебные материалы", search:"Поиск занятий и материалов", all:"Все", classes:"Местные занятия", materials:"Официальные материалы", call:"Позвонить", visit:"Открыть ресурс", none:"Ничего не найдено.", note:"Этот инструмент не является юридической консультацией и не определяет право на получение гражданства. Настоящий тест устный. USCIS может принять несколько вариантов ответа; проверяйте меняющиеся ответы непосредственно в USCIS." },
};

function shuffled<T>(items: T[], count: number) { return [...items].sort(() => Math.random() - 0.5).slice(0, count); }

export default function CitizenshipPage() {
  const { language } = useLanguage(); const t = copy[language];
  const [version, setVersion] = useState<TestVersion | "">(""); const [round, setRound] = useState<typeof studyCards["2008"]>([]); const [index, setIndex] = useState(0);
  const [responses, setResponses] = useState<Record<number, string>>({}); const [feedback, setFeedback] = useState<Record<number, Feedback>>({}); const [checking, setChecking] = useState(false); const [revealed, setRevealed] = useState(false); const [filter, setFilter] = useState("all"); const [query, setQuery] = useState("");
  const card = round[index];
  const translated = useTranslations(card ? [card.question,...card.answers] : []);
  const translatedResources = useTranslations(studyResources.flatMap(r=>[r.name,r.en,r.area])); const roundSize = version === "2025" ? 20 : 10;
  const resources = useMemo(() => studyResources.filter(r => (filter === "all" || r.kind === filter) && `${r.name} ${r.area} ${r.en} ${r.es} ${r.ru} ${translatedResources.get(r.en)||""} ${translatedResources.get(r.name)||""}`.toLowerCase().includes(query.toLowerCase())), [filter, query, translatedResources]);
  const startRound = (value: TestVersion) => { setVersion(value); setRound(shuffled(studyCards[value], value === "2025" ? 20 : 10)); setIndex(0); setResponses({}); setFeedback({}); setRevealed(false); };
  async function checkAnswer() { if (!card || !version || !responses[card.id]?.trim()) return; setChecking(true); try { const res = await fetch("/api/citizenship-feedback", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ version, questionId:card.id, response:responses[card.id], language }) }); const data = await res.json() as Feedback & { error?: string }; if (!res.ok) throw new Error(data.error || "Could not check answer"); setFeedback(previous => ({ ...previous, [card.id]:{...data,language} })); } catch { setFeedback(previous => ({ ...previous, [card.id]: { language, verdict:"unclear", feedback: language === "हिन्दी" ? "अभी उत्तर जाँचना संभव नहीं हुआ। आधिकारिक सूची से तुलना करें।" : language === "Español" ? "No pudimos revisar la respuesta ahora. Compare su respuesta con la lista oficial." : language === "Русский" ? "Сейчас не удалось проверить ответ. Сравните его с официальным списком." : "We could not check your answer right now. Compare it with the official list.", hint:"", mode:"official" } })); } finally { setChecking(false); } }
  function speak() { if (!card || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const spoken = translated.get(card.question); if (!spoken) return; const utterance = new SpeechSynthesisUtterance(spoken); utterance.lang = locale[language]; window.speechSynthesis.speak(utterance); }
  const reviewed = Object.keys(feedback).length;
  return <main className="more-page citizenship-page"><SiteNav current="citizenship" /><header className="citizenship-hero"><div className="eyebrow">{language === "हिन्दी" ? "लेक काउंटी · इलिनॉय" : language === "Русский" ? "ОКРУГ ЛЕЙК · ИЛЛИНОЙС" : language === "Español" ? "CONDADO DE LAKE · ILLINOIS" : "LAKE COUNTY · ILLINOIS"}</div><h1>{t.title}</h1><p>{t.intro}</p><div className="citizenship-jump"><a href="#test-version">{t.practice} ↓</a><a href="#study-resources">{t.directory} ↓</a></div></header>
    <section className="citizenship-section" aria-labelledby="test-version"><div className="citizenship-step">01 · {t.practice}</div><h2 id="test-version">{t.choose}</h2><div className="test-choices"><button className={version === "2008" ? "active" : ""} onClick={() => startRound("2008")} aria-pressed={version === "2008"}><span className="version-badge">2008</span><span>{t.before}</span><span aria-hidden="true">→</span></button><button className={version === "2025" ? "active" : ""} onClick={() => startRound("2025")} aria-pressed={version === "2025"}><span className="version-badge">2025</span><span>{t.after}</span><span aria-hidden="true">→</span></button></div><p className="muted">{t.unsure} <a href="https://www.usa.gov/naturalization" target="_blank" rel="noopener noreferrer">USAGov ↗</a></p></section>
    {version && <section className="citizenship-section" aria-labelledby="practice-title"><div className="section-heading"><div><h2 id="practice-title">{t.practice} · {version}</h2><p>{t.round}</p></div><strong>{t.progress} {reviewed} / {roundSize}</strong></div>{card ? <article className="study-card"><div className="study-count">{t.question} {index + 1} / {round.length}</div><h3><TranslatedText text={card.question} translations={translated}/></h3><TranslationNotice translations={translated}/>{language !== "English" && <details><summary>{translationStatus[language].original}</summary><p lang="en">{card.question}</p></details>}{language !== "English" && <p className="question-translation">{t.englishNote}</p>}<button className="listen-button" onClick={speak} disabled={!translated.get(card.question)}>🔊 {t.listen}</button><label className="answer-entry"><span>{t.answer}</span><textarea value={responses[card.id] || ""} onChange={event => setResponses(prev => ({ ...prev, [card.id]:event.target.value }))} placeholder={t.placeholder} rows={3} /><button onClick={checkAnswer} disabled={checking || !responses[card.id]?.trim()}>{checking ? t.checking : t.check}</button></label>{feedback[card.id] && feedback[card.id].language !== language && <p role="status">{translationStatus[language].feedback}</p>}{feedback[card.id]?.language === language && <div className={`answer-feedback ${feedback[card.id].verdict}`} role="status"><strong>{feedback[card.id].feedback}</strong>{feedback[card.id].hint && <p>{feedback[card.id].hint}</p>}</div>}<button className="reveal-button" onClick={() => setRevealed(value => !value)} aria-expanded={revealed}>{revealed ? t.hide : t.reveal}</button>{revealed && <div className="study-answer" role="status"><strong>{t.official}</strong><ul>{card.answers.map(answer => <li key={answer}><TranslatedText text={answer} translations={translated}/>{language !== "English" && <details><summary>{translationStatus[language].original}</summary><span lang="en">{answer}</span></details>}</li>)}</ul></div>}<div className="study-footer"><button disabled={index === 0} onClick={() => { setIndex(i => i - 1); setRevealed(false); }}>{t.previous}</button><button onClick={() => { setIndex(i => Math.min(i + 1, round.length)); setRevealed(false); }}>{t.next}</button></div></article> : <div className="study-card"><h3>{t.complete}</h3><p>{t.progress} {reviewed} / {roundSize}</p><button onClick={() => startRound(version)}>{t.restart}</button></div>}<div className="study-footer"><a href={officialLists[version]} target="_blank" rel="noopener noreferrer">{t.list} ↗</a></div></section>}
    <section className="citizenship-section" id="study-resources" aria-labelledby="study-resources-title"><div className="citizenship-step">02 · {t.directory}</div><h2 id="study-resources-title">{t.directory}</h2><div className="resource-filters"><label><span className="sr-only">{t.search}</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={t.search} /></label><div role="group" aria-label={t.directory}>{[["all",t.all],["class",t.classes],["official",t.materials]].map(([value,label]) => <button key={value} className={filter === value ? "active" : ""} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div></div><TranslationNotice translations={translatedResources}/><div className="study-resource-grid">{resources.map(resource => <article className="pathway-card" key={resource.id}><span className="study-kind">{resource.kind === "class" ? t.classes : t.materials}</span><h3><TranslatedText text={resource.name} translations={translatedResources}/></h3><p><TranslatedText text={resource.en} translations={translatedResources}/></p><span><TranslatedText text={resource.area} translations={translatedResources}/></span><div className="study-resource-links"><a href={`tel:${resource.phone.replace(/[^\d]/g, "")}`}>{t.call} {resource.phone}</a><a href={resource.url} target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></div></article>)}{resources.length === 0 && <p>{t.none}</p>}</div></section><p className="more-note">{t.note}</p></main>;
}
