"use client";

import { useMemo, useState } from "react";
import { SiteNav, useLanguage } from "../language";
import { officialLists, studyCards, studyResources, type TestVersion } from "./study-data";

const copy = {
  English: { title:"Study for the citizenship test", intro:"Practice a few civics questions aloud, then use the complete USCIS list and local classes to keep studying.", choose:"Which civics test applies?", before:"I filed Form N-400 before October 20, 2025", after:"I filed on or after October 20, 2025", unsure:"Not sure? Check your N-400 filing date or ask a qualified organization. This tool cannot determine your test version.", practice:"Practice questions", sample:"This is a short practice set, not the full USCIS test or a passing score.", card:"Question", reveal:"Show an accepted answer", hide:"Hide answer", know:"I knew it", review:"Practice again", next:"Next question", previous:"Previous", complete:"Set complete", restart:"Start again", progress:"You knew", of:"of", list:"Open the complete official question list", listen:"Read question aloud", directory:"Classes and study resources", search:"Search classes or resources", all:"All", classes:"Local classes", official:"Official study materials", call:"Call", visit:"Open resource", none:"No matching resources.", note:"Questions are adapted from USCIS study lists. The real civics test is oral and may have more than one accepted answer. Most applicants also take an English test; exceptions or accommodations may apply. Check USCIS for current answers and requirements." },
  Español: { title:"Estudie para el examen de ciudadanía", intro:"Practique algunas preguntas de civismo en voz alta y use la lista completa de USCIS y las clases locales para seguir estudiando.", choose:"¿Qué examen de civismo le corresponde?", before:"Presenté el formulario N-400 antes del 20 de octubre de 2025", after:"Lo presenté el 20 de octubre de 2025 o después", unsure:"¿No está seguro? Revise la fecha de presentación del N-400 o consulte a una organización calificada. Esta herramienta no determina su versión.", practice:"Preguntas de práctica", sample:"Esta es una muestra breve, no el examen completo de USCIS ni una calificación aprobatoria.", card:"Pregunta", reveal:"Mostrar una respuesta aceptada", hide:"Ocultar respuesta", know:"La sabía", review:"Practicar de nuevo", next:"Siguiente pregunta", previous:"Anterior", complete:"Serie terminada", restart:"Empezar de nuevo", progress:"Sabía", of:"de", list:"Abrir lista oficial completa", listen:"Escuchar pregunta", directory:"Clases y recursos de estudio", search:"Buscar clases o recursos", all:"Todos", classes:"Clases locales", official:"Materiales oficiales", call:"Llamar", visit:"Abrir recurso", none:"No hay recursos que coincidan.", note:"Las preguntas se adaptaron de las listas de USCIS. El examen real es oral y puede aceptar varias respuestas. La mayoría de solicitantes también toman un examen de inglés; puede haber excepciones o adaptaciones. Consulte USCIS para ver requisitos y respuestas actuales." },
  Русский: { title:"Подготовка к тесту на гражданство", intro:"Потренируйтесь отвечать на несколько вопросов устно, затем используйте полный список USCIS и местные занятия.", choose:"Какая версия теста по граждановедению вам подходит?", before:"Я подал(а) форму N-400 до 20 октября 2025 года", after:"Я подал(а) форму 20 октября 2025 года или позже", unsure:"Не уверены? Проверьте дату подачи N-400 или спросите в квалифицированной организации. Этот инструмент не определяет вашу версию теста.", practice:"Практические вопросы", sample:"Это короткая тренировка, а не полный тест USCIS или проходной балл.", card:"Вопрос", reveal:"Показать допустимый ответ", hide:"Скрыть ответ", know:"Я знал(а)", review:"Повторить", next:"Следующий вопрос", previous:"Предыдущий", complete:"Набор завершён", restart:"Начать заново", progress:"Вы знали", of:"из", list:"Открыть полный официальный список", listen:"Прослушать вопрос", directory:"Занятия и учебные материалы", search:"Поиск занятий и материалов", all:"Все", classes:"Местные занятия", official:"Официальные материалы", call:"Позвонить", visit:"Открыть ресурс", none:"Ничего не найдено.", note:"Вопросы адаптированы из списков USCIS. Настоящий тест устный и может допускать несколько ответов. Большинство заявителей также сдают тест по английскому; возможны исключения и специальные условия. Проверяйте актуальные ответы и требования на сайте USCIS." },
};

export default function CitizenshipPage() {
  const { language } = useLanguage();
  const t = copy[language];
  const [version, setVersion] = useState<TestVersion | "">("");
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [known, setKnown] = useState<Record<string, boolean>>({});
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const cards = version ? studyCards[version] : [];
  const card = cards[index];
  const score = cards.filter((_, i) => known[`${version}-${i}`]).length;
  const resources = useMemo(() => studyResources.filter(r => (filter === "all" || r.kind === filter) && `${r.name} ${r.area} ${r.en} ${r.es} ${r.ru}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  function selectVersion(value: TestVersion) { setVersion(value); setIndex(0); setRevealed(false); }
  function advance(didKnow: boolean) { if (!version) return; setKnown(previous => ({ ...previous, [`${version}-${index}`]: didKnow })); setRevealed(false); setIndex(current => Math.min(current + 1, cards.length)); }
  function speak() { if (!card || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const speech = new SpeechSynthesisUtterance(card.question); speech.lang = "en-US"; window.speechSynthesis.speak(speech); }

  return <main className="more-page citizenship-page"><SiteNav current="citizenship" /><header className="more-heading"><div className="eyebrow">LAKE COUNTY · ILLINOIS</div><h1>{t.title}</h1><p>{t.intro}</p></header>
    <section className="citizenship-section" aria-labelledby="test-version"><h2 id="test-version">{t.choose}</h2><div className="test-choices"><button className={version === "2008" ? "active" : ""} onClick={() => selectVersion("2008")} aria-pressed={version === "2008"}>{t.before}<strong>2008</strong></button><button className={version === "2025" ? "active" : ""} onClick={() => selectVersion("2025")} aria-pressed={version === "2025"}>{t.after}<strong>2025</strong></button></div><p className="muted">{t.unsure}</p><a className="official-link" href="https://www.usa.gov/naturalization" target="_blank" rel="noopener noreferrer">USAGov ↗</a></section>
    {version && <section className="citizenship-section" aria-labelledby="practice-title"><div className="section-heading"><div><h2 id="practice-title">{t.practice} · {version}</h2><p>{t.sample}</p></div><strong>{t.progress} {score} {t.of} {cards.length}</strong></div>{card ? <article className="study-card"><div className="study-count">{t.card} {index + 1} / {cards.length}</div><h3 lang="en">{card.question}</h3>{language !== "English" && <p className="question-translation" lang={language === "Español" ? "es" : "ru"}>{language === "Español" ? card.es : card.ru}</p>}<div className="study-actions"><button onClick={speak}>🔊 {t.listen}</button><button onClick={() => setRevealed(value => !value)} aria-expanded={revealed}>{revealed ? t.hide : t.reveal}</button></div>{revealed && <div className="study-answer" role="status"><strong lang="en">{card.answer}</strong><div className="study-actions"><button onClick={() => advance(true)}>{t.know}</button><button onClick={() => advance(false)}>{t.review}</button></div></div>}</article> : <div className="study-card"><h3>{t.complete}</h3><p>{t.progress} {score} {t.of} {cards.length}</p><button onClick={() => { setIndex(0); setRevealed(false); }}>{t.restart}</button></div>}<div className="study-footer"><button disabled={index === 0} onClick={() => { setIndex(i => i - 1); setRevealed(false); }}>{t.previous}</button><a href={officialLists[version]} target="_blank" rel="noopener noreferrer">{t.list} ↗</a></div></section>}
    <section className="citizenship-section" aria-labelledby="study-resources"><h2 id="study-resources">{t.directory}</h2><div className="resource-filters"><label><span className="sr-only">{t.search}</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={t.search} /></label><div role="group" aria-label={t.directory}>{[["all",t.all],["class",t.classes],["official",t.official]].map(([value,label]) => <button key={value} className={filter === value ? "active" : ""} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div></div><div className="study-resource-grid">{resources.map(resource => <article className="pathway-card" key={resource.id}><span className="study-kind">{resource.kind === "class" ? t.classes : t.official}</span><h3>{resource.name}</h3><p>{resource[language === "Español" ? "es" : language === "Русский" ? "ru" : "en"]}</p><span>{resource.area}</span><div className="study-resource-links"><a href={`tel:${resource.phone.replace(/[^\d]/g, "")}`}>{t.call} {resource.phone}</a><a href={resource.url} target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></div></article>)}{resources.length === 0 && <p>{t.none}</p>}</div></section><p className="more-note">{t.note}</p></main>;
}
