"use client";
import { hindiMore } from "../hindi";
import { SiteNav, useLanguage } from "../language";

import { groups } from "./data";
import { useTranslations, TranslatedText, TranslationNotice } from "../translations";
const translations = {
  हिन्दी: hindiMore,
  English: { title:"More ways to get help", intro:"Official forms, local organizations, and places to follow updates. Check each organization’s latest rules and hours before visiting.", groups:["Local help and organizations","Legal rights and official forms","Health, money, and education","Updates and newsletters"], note:"Links reviewed September 14, 2026. Services and eligibility can change. For immediate local help, call 211.", descriptions:groups.map(group=>group.items.map(item=>item[1])) },
  Español: { title:"Más formas de obtener ayuda", intro:"Formularios oficiales, organizaciones locales y fuentes de noticias. Revise las reglas y horarios actuales antes de visitar.", groups:["Ayuda y organizaciones locales","Derechos legales y formularios oficiales","Salud, dinero y educación","Noticias y boletines"], note:"Enlaces revisados el 14 de septiembre de 2026. Los servicios y requisitos pueden cambiar. Para ayuda local inmediata, llame al 211.", descriptions:[["Encuentre alimentos, refugio, atención médica y otra ayuda local a cualquier hora.","Apoyo para familias inmigrantes, educación para ciudadanía y orientación legal en Lake County.","Pregunte por servicios legales de inmigración, vivienda y violencia doméstica.","Clases de inglés, equivalencia de secundaria, informática y ciudadanía.","Servicios de empleo, capacitación y búsqueda de trabajo."],["Enlaces estatales sobre derechos, ayuda legal y centros de bienvenida.","Información legal de Illinois, formularios y ayuda para encontrar un abogado.","Información y referencias legales para recién llegados a Illinois.","Formularios e instrucciones oficiales de inmigración; los formularios en blanco son gratis.","Presente ciertos formularios en línea y consulte el estado de su caso."],["Información actual sobre programas estatales de salud y cambios en los requisitos.","Solicite SNAP, Medicaid y ayuda económica mediante el estado.","Vía de ayuda financiera estatal para algunos estudiantes que no pueden usar FAFSA; confirme disponibilidad.","Consulte los requisitos de ayuda federal y solicite ayuda para estudios universitarios.","Busque centros voluntarios del IRS que puedan ayudar con el formulario W-7 y el ITIN."],["Suscríbase a noticias de su representante del condado.","Lea información legal actual de Illinois y suscríbase a noticias.","Orientación del condado y contactos del 211 para necesidades urgentes."]] },
  Русский: { title:"Другие способы получить помощь", intro:"Официальные формы, местные организации и источники новостей. Перед посещением уточняйте актуальные правила и часы работы.", groups:["Местная помощь и организации","Юридические права и официальные формы","Здоровье, финансы и образование","Новости и рассылки"], note:"Ссылки проверены 14 сентября 2026 года. Услуги и условия могут измениться. Для срочной местной помощи позвоните 211.", descriptions:[["Ищите продукты, жильё, медицинскую и другую местную помощь в любое время.","Поддержка семей иммигрантов, подготовка к гражданству и юридическая помощь в округе Лейк.","Узнайте о помощи по вопросам иммиграции, жилья и домашнего насилия.","Занятия по английскому, школьному образованию, компьютерам и гражданству.","Помощь с трудоустройством, обучением и поиском работы."],["Ссылки штата на информацию о правах, юридическую помощь и центры поддержки.","Правовая информация Иллинойса, формы и помощь в поиске юриста.","Правовая информация и направления для недавно прибывших в штат.","Официальные иммиграционные формы и инструкции; пустые формы бесплатны.","Подавайте доступные формы онлайн и отслеживайте своё дело."],["Актуальная информация о программах здравоохранения и изменениях условий.","Подайте заявку на SNAP, Medicaid и денежную помощь через сайт штата.","Возможность помощи студентам, которые не могут использовать FAFSA; уточняйте доступность.","Проверьте право на федеральную помощь и подайте заявку на оплату учёбы.","Найдите центры IRS, где могут помочь с формой W-7 и ITIN."],["Подпишитесь на новости представителя совета округа.","Читайте актуальную правовую информацию Иллинойса и новости.","Информация округа и контакты 211 для срочных нужд."]] },
};

export default function MoreResources() {
  const { language } = useLanguage();
  const t = translations[language];
  const names = useTranslations(groups.flatMap(g=>g.items.map(i=>i[0])));
  return <main className="more-page">
    <SiteNav current="more" />
    <header className="more-heading"><div className="eyebrow">{language === "हिन्दी" ? "लेक काउंटी · इलिनॉय" : language === "Русский" ? "ОКРУГ ЛЕЙК · ИЛЛИНОЙС" : language === "Español" ? "CONDADO DE LAKE · ILLINOIS" : "LAKE COUNTY · ILLINOIS"}</div><h1>{t.title}</h1><p>{t.intro}</p></header>
    <TranslationNotice translations={names}/>{groups.map((group,i)=><section className="more-group" key={group.title}><h2>{t.groups[i]}</h2><div className="more-grid">{group.items.map(([name,,url],j)=><a className="more-item" href={url} target="_blank" rel="noopener noreferrer" key={name}><strong><TranslatedText text={name} translations={names}/> <span aria-hidden="true">↗</span></strong><span>{t.descriptions[i][j]}</span></a>)}</div></section>)}
    <p className="more-note">{t.note}</p>
  </main>;
}
