export type Resource = {
  id: string; name: string; categories: string[]; languages: string[];
  address: string; city: string; zip: string; county: string; phone: string;
  website: string; hours: string; appointment: string; description: string;
  verifiedAt: string; source: string;
};

export const categories = ["Legal aid", "Healthcare", "Education", "Housing", "Food assistance", "Employment", "Language / ESL", "Financial / tax help"];
export const initialResources: Resource[] = [
  { id:"haces", name:"HACES", categories:["Legal aid","Education","Financial / tax help"], languages:["English","Spanish"], address:"820 W Greenwood Ave, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-244-0300", website:"https://haces.org/", hours:"Mon–Fri, 9 am–5:30 pm", appointment:"Yes, for consultations", description:"Immigration guidance, citizenship classes and support for immigrant families; call about eligibility.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/5221/Hispanic-American-Community-Education-an" },
  { id:"lake-health", name:"Lake County Health Department & Community Health Center", categories:["Healthcare"], languages:["English","Spanish"], address:"3010 Grand Ave, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-377-8000", website:"https://www.lakecountyil.gov/2642/Directory-of-Services", hours:"Call for clinic hours", appointment:"Call to confirm", description:"Primary care and other health services; no resident is turned away for inability to pay.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/2642/Directory-of-Services" },
  { id:"clc-esl", name:"College of Lake County — Adult Education & ESL", categories:["Education","Language / ESL"], languages:["English","Spanish"], address:"1120 S Milwaukee Ave, Vernon Hills, IL 60061", city:"Vernon Hills", zip:"60061", county:"Lake", phone:"847-543-2485", website:"https://www.clcillinois.edu/programs-and-classes/adult-education-and-esl", hours:"Class and testing times vary; call for schedule", appointment:"Enrollment and placement required", description:"ESL and adult education for Illinois residents, with priority for Lake County.", verifiedAt:"2026-09-14", source:"https://www.clcillinois.edu/programs-and-classes/adult-education-and-esl" },
  { id:"job-center", name:"Job Center of Lake County", categories:["Employment","Education"], languages:["English"], address:"1 N Genesee St, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-377-3450", website:"https://www.lakecountyil.gov/4927/Job-Center-of-Lake-County", hours:"Weekdays, 8:30 am–4 pm; closed noon–1 pm", appointment:"Call to confirm", description:"Job search, training and career services, including support for immigrants.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/168/About-the-Job-Center" },
  { id:"211", name:"211 Lake County", categories:["Housing","Food assistance","Healthcare","Employment","Financial / tax help"], languages:["English","Spanish","Russian","Polish"], address:"Phone and online service throughout Lake County", city:"Countywide", zip:"", county:"Lake", phone:"211 or 855-677-5253", website:"https://search.211lakecounty.org/", hours:"24 hours, every day", appointment:"No", description:"Free, confidential referrals for food, shelter, rent, utilities, health and more; interpreters available.", verifiedAt:"2026-09-14", source:"https://211lakecounty.org/images/Toolkit/211_Frequently_Asked_Questions_FAQs.pdf" },
  { id:"north-suburban-legal", name:"North Suburban Legal Aid Clinic", categories:["Legal aid"], languages:["English","Spanish","Polish"], address:"3500 Western Ave, Highland Park, IL 60035", city:"Highland Park", zip:"60035", county:"Lake", phone:"847-737-4042", website:"https://nslegalaid.org/", hours:"Mon–Fri, 9 am–5 pm", appointment:"Yes", description:"Free civil legal help for low-income residents, including immigration, housing and family matters.", verifiedAt:"2026-09-14", source:"https://nslegalaid.org/" },
  { id:"painesville-food", name:"PADS Lake County", categories:["Housing","Food assistance"], languages:["English","Spanish"], address:"1800 Grand Ave, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-609-0153", website:"https://padslakecounty.org/", hours:"Call for shelter and meal hours", appointment:"Call to confirm", description:"Emergency shelter, meals and housing navigation for people experiencing homelessness.", verifiedAt:"2026-09-14", source:"https://padslakecounty.org/" },
  { id:"immigrant-support", name:"Immigrant Support Network", categories:["Employment","Language / ESL","Education"], languages:["English","Spanish","Russian"], address:"1810 S Highland Ave, Arlington Heights, IL 60005", city:"Arlington Heights", zip:"60005", county:"Lake", phone:"847-818-8400", website:"https://www.immigrantsupport.org/", hours:"Mon–Thu, 10 am–4 pm", appointment:"Call to confirm", description:"Workforce navigation, English practice groups and referrals for immigrant families.", verifiedAt:"2026-09-14", source:"https://www.immigrantsupport.org/" },
  { id:"lake-county-vets", name:"Lake County Workforce Development", categories:["Employment","Financial / tax help"], languages:["English","Spanish"], address:"1 N Genesee St, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-377-3450", website:"https://www.lakecountyil.gov/4927/Job-Center-of-Lake-County", hours:"Weekdays, 8:30 am–4 pm", appointment:"Call to confirm", description:"No-cost job training, resume help and benefits navigation for eligible adults.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/4927/Job-Center-of-Lake-County" },
  { id:"uscis-forms", name:"USCIS Forms & Filing Help", categories:["Legal aid","Financial / tax help"], languages:["English","Spanish"], address:"Online and by phone", city:"Countywide", zip:"", county:"Lake", phone:"800-375-5283", website:"https://www.uscis.gov/forms", hours:"Online 24/7; phone Mon–Fri", appointment:"No", description:"Official forms for work permits, citizenship, family petitions and fee waivers; never pay for blank forms.", verifiedAt:"2026-09-14", source:"https://www.uscis.gov/forms" },
  { id:"fafsa", name:"FAFSA & Federal Student Aid", categories:["Education","Financial / tax help"], languages:["English","Spanish"], address:"Online at studentaid.gov", city:"Countywide", zip:"", county:"Lake", phone:"800-433-3243", website:"https://studentaid.gov/h/apply-for-aid/fafsa", hours:"Online 24/7; call Mon–Fri", appointment:"No", description:"Free application for college grants, work-study and loans; students without an SSN can review eligible aid options.", verifiedAt:"2026-09-14", source:"https://studentaid.gov/h/apply-for-aid/fafsa" },
  { id:"illinois-benefits", name:"Illinois ABE Benefits (SNAP, Medicaid, Cash)", categories:["Food assistance","Healthcare","Financial / tax help"], languages:["English","Spanish","Polish"], address:"Online at abe.illinois.gov", city:"Countywide", zip:"", county:"Lake", phone:"800-843-6154", website:"https://abe.illinois.gov/abe/access/", hours:"Online 24/7; call Mon–Fri", appointment:"No", description:"Apply for SNAP food benefits, Medicaid and cash assistance through Illinois’ official portal.", verifiedAt:"2026-09-14", source:"https://abe.illinois.gov/abe/access/" },
]; 
