export type Resource = {
  id: string; name: string; categories: string[]; languages: string[];
  address: string; city: string; zip: string; county: string; phone: string;
  website: string; hours: string; appointment: string; description: string;
  verifiedAt: string; source: string;
};

export const categories = ["Legal aid", "Healthcare", "Education", "Housing", "Food assistance", "Employment", "Language / ESL", "Financial / tax help"];
export const initialResources: Resource[] = [
  { id:"haces", name:"HACES", categories:["Legal aid","Education","Financial / tax help"], languages:["English","Spanish"], address:"820 W Greenwood Ave, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-244-0300", website:"https://haces.org/", hours:"Mon–Fri, 9 am–5:30 pm", appointment:"Yes, for consultations", description:"Immigration guidance, citizenship classes and support for immigrant families; call about eligibility.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/5221/Hispanic-American-Community-Education-an" },
  { id:"lake-health", name:"Lake County Health Department & Community Health Center", categories:["Healthcare"], languages:["English","Spanish"], address:"3010 Grand Ave, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-377-8000", website:"https://www.lakecountyil.gov/2642/Directory-of-Services", hours:"Call for clinic hours", appointment:"Call to confirm", description:"Primary care and other health services; no resident is turned away for inability to pay.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/2642/Directory-of-Services" },
  { id:"clc-esl", name:"College of Lake County — Adult Education & ESL", categories:["Education","Language / ESL"], languages:["English","Spanish"], address:"1120 S Milwaukee Ave, Vernon Hills, IL 60061", city:"Vernon Hills", zip:"60061", county:"Lake", phone:"847-543-2485", website:"https://www.clcillinois.edu/programs-and-classes/adult-education-and-esl", hours:"Class and testing times vary; call for schedule", appointment:"Enrollment and placement required", description:"ESL and adult education for Illinois residents, with priority for Lake County.", verifiedAt:"2026-09-14", source:"https://www.clcillinois.edu/programs-and-classes/adult-education-and-esl" },
  { id:"job-center", name:"Job Center of Lake County", categories:["Employment","Education"], languages:["English"], address:"1 N Genesee St, Waukegan, IL 60085", city:"Waukegan", zip:"60085", county:"Lake", phone:"847-377-3450", website:"https://www.lakecountyil.gov/4927/Job-Center-of-Lake-County", hours:"Weekdays, 8:30 am–4 pm; closed noon–1 pm", appointment:"Call to confirm", description:"Job search, training and career services, including support for immigrants.", verifiedAt:"2026-09-14", source:"https://www.lakecountyil.gov/168/About-the-Job-Center" },
  { id:"211", name:"211 Lake County", categories:["Housing","Food assistance","Healthcare","Employment","Financial / tax help"], languages:["English","Spanish","Russian","Polish"], address:"Phone and online service throughout Lake County", city:"Countywide", zip:"", county:"Lake", phone:"211 or 855-677-5253", website:"https://search.211lakecounty.org/", hours:"24 hours, every day", appointment:"No", description:"Free, confidential referrals for food, shelter, rent, utilities, health and more; interpreters available.", verifiedAt:"2026-09-14", source:"https://211lakecounty.org/images/Toolkit/211_Frequently_Asked_Questions_FAQs.pdf" },
];
