"use client";
import { hindiDirectory, hindiCategories } from "./hindi";
import { useEffect, useMemo, useState } from "react";
import { Search, MapPin, Phone, Globe2, Clock3, CalendarDays, Download, Plus, ArrowUpRight } from "lucide-react";
import { categories, type Resource } from "./resources";
import { SiteNav, useLanguage, type Language } from "./language";
import { useTranslations, TranslatedText, TranslationNotice } from "./translations";
import { label, languageNames, locale, translationStatus } from "./locale";
import { resourceDescription } from "./resource-translations";

const copy = {
  हिन्दी: hindiDirectory,
  English: { title:"Find local help", intro:"Immigrant resources in Lake County, Illinois", search:"Search organizations or services", category:"Category", language:"Service language", location:"ZIP code or county", all:"All", results:"resources", noResults:"No matches. Try clearing a filter or call 211 for help finding services.", submit:"Request an update", verified:"Last verified", appointment:"Appointment", source:"Source", formTitle:"Add or update a resource", formIntro:"Organizations can send changes for review. Nothing appears publicly until approved.", name:"Organization name", address:"Address", phone:"Phone", hours:"Hours", description:"Eligibility / services (one line)", email:"Your contact email", send:"Send for review", sent:"Thank you. Your request is waiting for review.", error:"Could not send your request. Please try again.", close:"Close", pdf:"Print / save PDF", csv:"Download CSV", note:"Call ahead to confirm hours, language access and eligibility." },
  Español: { title:"Encuentre ayuda local", intro:"Recursos para inmigrantes en el condado de Lake, Illinois", search:"Buscar organizaciones o servicios", category:"Categoría", language:"Idioma del servicio", location:"Código postal o condado", all:"Todos", results:"recursos", noResults:"No hay resultados. Quite un filtro o llame al 211 para pedir ayuda.", submit:"Solicitar un cambio", verified:"Última verificación", appointment:"Cita", source:"Fuente", formTitle:"Agregar o actualizar un recurso", formIntro:"Las organizaciones pueden enviar cambios para revisión. Nada se publica sin aprobación.", name:"Nombre de la organización", address:"Dirección", phone:"Teléfono", hours:"Horario", description:"Elegibilidad / servicios (una línea)", email:"Su correo electrónico", send:"Enviar para revisión", sent:"Gracias. Su solicitud está pendiente de revisión.", error:"No se pudo enviar. Inténtelo de nuevo.", close:"Cerrar", pdf:"Imprimir / guardar PDF", csv:"Descargar CSV", note:"Llame antes para confirmar horarios, idiomas y requisitos." },
  Русский: { title:"Найдите помощь рядом", intro:"Ресурсы для иммигрантов в округе Лейк, Иллинойс", search:"Поиск организаций и услуг", category:"Категория", language:"Язык обслуживания", location:"Почтовый индекс или округ", all:"Все", results:"ресурсов", noResults:"Ничего не найдено. Сбросьте фильтр или позвоните 211.", submit:"Предложить изменение", verified:"Проверено", appointment:"Запись", source:"Источник", formTitle:"Добавить или обновить ресурс", formIntro:"Организации могут отправить сведения на проверку. Изменения публикуются после одобрения.", name:"Название организации", address:"Адрес", phone:"Телефон", hours:"Часы работы", description:"Условия / услуги (одна строка)", email:"Ваш адрес эл. почты", send:"Отправить на проверку", sent:"Спасибо. Запрос ожидает рассмотрения.", error:"Не удалось отправить запрос. Попробуйте еще раз.", close:"Закрыть", pdf:"Печать / сохранить PDF", csv:"Скачать CSV", note:"Позвоните заранее, чтобы уточнить часы работы, языки и условия." }
};
type Lang = Language;
const categoryLabels: Record<Lang, Record<string,string>> = {
  हिन्दी: hindiCategories,
  English: Object.fromEntries(categories.map(c=>[c,c])),
  Español: {"Legal aid":"Ayuda legal","Healthcare":"Salud","Education":"Educación","Housing":"Vivienda","Food assistance":"Alimentos","Employment":"Empleo","Language / ESL":"Clases de inglés","Financial / tax help":"Ayuda financiera / impuestos"},
  Русский: {"Legal aid":"Юридическая помощь","Healthcare":"Здравоохранение","Education":"Образование","Housing":"Жилье","Food assistance":"Продовольственная помощь","Employment":"Работа","Language / ESL":"Английский язык","Financial / tax help":"Финансы / налоги"}
};
const csvCell = (v: unknown) => `"${String(v ?? "").replaceAll('"','""')}"`;
export default function Directory({ initial }: { initial: Resource[] }) {
  const [records,setRecords] = useState(initial);
  const { language: ui } = useLanguage();
  const [q,setQ] = useState(""), [category,setCategory] = useState(""), [language,setLanguage] = useState(""), [location,setLocation] = useState("");
  const [showForm,setShowForm] = useState(false), [status,setStatus] = useState(""), [busy,setBusy] = useState(false);
  const t = copy[ui];
  const translated = useTranslations(records.flatMap(r=>[r.description,r.hours,r.appointment,...(!r.zip ? [r.address] : [])]));
  const tr = (value:string) => <TranslatedText text={value} translations={translated}/>;
  useEffect(() => { fetch("/api/resources").then(r => r.ok ? r.json() : null).then(d => { if(Array.isArray(d)) setRecords(d); }).catch(()=>{}); }, []);
  useEffect(() => {
    type ModelContext = {registerTool:(tool:object, options:{signal:AbortSignal})=>void|Promise<void>};
    const context=(document as Document & {modelContext?:ModelContext}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    Promise.resolve(context.registerTool({name:"filter_lake_county_resources",title:"Filter local resources",description:"Apply category, service language, and location filters to the visible Lake County resource directory.",inputSchema:{type:"object",properties:{category:{type:"string"},language:{type:"string"},location:{type:"string"},query:{type:"string"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=="object")throw Error("Invalid filters");const v=input as Record<string,unknown>;for(const x of Object.values(v))if(typeof x!=="string")throw Error("Filters must be text");if(v.category&&!categories.includes(v.category as string))throw Error("Unknown category");setCategory((v.category as string)||"");setLanguage((v.language as string)||"");setLocation((v.location as string)||"");setQ((v.query as string)||"");return {applied:true};}}, {signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[]);
  const filtered = useMemo(() => records.filter(r => (!q || [r.name,r.description,resourceDescription(r.id,r.description,ui),translated.get(r.description)||"",r.city,...r.categories,...r.categories.map(c=>categoryLabels[ui][c]||c)].join(" ").toLowerCase().includes(q.toLowerCase())) && (!category || r.categories.includes(category)) && (!language || r.languages.includes(language)) && (!location || [r.zip,r.county,r.city,r.address].join(" ").toLowerCase().includes(location.toLowerCase()))),[records,q,category,language,location,ui,translated]);
  const exportCsv = () => { const cols: (keyof Resource)[] = ["name","categories","languages","address","phone","website","hours","appointment","description","verifiedAt","source"]; const headers = [t.name,t.category,t.language,t.address,t.phone,label(ui,"Website","Sitio web","Сайт","वेबसाइट"),t.hours,t.appointment,t.description,t.verified,t.source]; const lines=[headers.map(csvCell).join(","),...records.map(r=>cols.map(k=>csvCell(k==="categories" ? r.categories.map(c=>categoryLabels[ui][c]||c).join("; ") : k==="languages" ? r.languages.map(l=>languageNames[ui][l]||l).join("; ") : ["description","hours","appointment"].includes(k) ? translated.get(String(r[k])) || translationStatus[ui].failed : r[k])).join(","))]; const url=URL.createObjectURL(new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a");a.href=url;a.download="lake-county-immigrant-resources.csv";a.click();URL.revokeObjectURL(url); };
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true);setStatus(""); const data=Object.fromEntries(new FormData(e.currentTarget).entries()); const r=await fetch("/api/submissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}).catch(()=>null); setBusy(false);if(r?.ok){setStatus("sent"); (e.target as HTMLFormElement).reset();}else setStatus("error"); }
  return <main className="shell"><header className="topbar"><div className="brand"><span className="mark">✳</span><span>Lake County<br/><strong>{label(ui,"Resource Guide","Guía de recursos","Справочник ресурсов","संसाधन मार्गदर्शिका")}</strong></span></div></header><SiteNav current="directory" />
    <section className="heading"><div><div className="eyebrow">{label(ui,"VERNON HILLS · LAKE COUNTY, IL","VERNON HILLS · CONDADO DE LAKE, IL","ВЕРНОН-ХИЛЛС · ОКРУГ ЛЕЙК, IL","वर्नन हिल्स · लेक काउंटी, IL")}</div><h1>{t.title}<span className="period">.</span></h1><p>{t.intro}</p></div><div className="heading-actions"><button onClick={()=>{setStatus("");setShowForm(true)}} className="primary"><Plus size={18}/>{t.submit}</button><div className="export-group"><button disabled={translated.loading || translated.failed} onClick={exportCsv}><Download size={17}/>{t.csv}</button><button onClick={()=>{setQ("");setCategory("");setLanguage("");setLocation("");setTimeout(()=>window.print(),100)}}>{t.pdf}</button></div></div></section>
    <section className="urgent-strip"><strong>{ui === "हिन्दी" ? "आज मदद चाहिए?" : ui === "Español" ? "¿Necesita ayuda hoy?" : ui === "Русский" ? "Нужна помощь сегодня?" : "Need help today?"}</strong><span>{ui === "हिन्दी" ? "भोजन, आश्रय, स्वास्थ्य या अन्य तत्काल स्थानीय मदद के लिए 211 पर कॉल करें।" : ui === "Español" ? "Llame al 211 para pedir ayuda urgente con alimentos, refugio, salud y otras necesidades locales." : ui === "Русский" ? "Позвоните 211, если срочно нужна еда, жильё, медицинская или другая местная помощь." : "Call 211 for food, shelter, health, or other urgent local needs."}</span><a href="tel:211">{ui === "हिन्दी" ? "211 पर कॉल करें →" : ui === "Español" ? "Llame al 211 →" : ui === "Русский" ? "Позвонить 211 →" : "Call 211 →"}</a></section>
    <section className="finder" aria-label={t.search}><label className="searchbox"><Search size={21}/><input aria-label={t.search} placeholder={t.search} value={q} onChange={e=>setQ(e.target.value)}/></label><div className="category-chips" aria-label={t.category}><button className={!category?"selected":""} onClick={()=>setCategory("")}>{t.all}</button>{categories.map(c=><button key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{categoryLabels[ui][c]}</button>)}</div><div className="filter-row"><label><span>{t.category}</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{categories.map(c=><option key={c} value={c}>{categoryLabels[ui][c]}</option>)}</select></label><label><span>{t.language}</span><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">{t.all}</option>{[...new Set(records.flatMap(r=>r.languages))].map(l=><option key={l} value={l}>{languageNames[ui][l]||l}</option>)}</select></label><label><span>{t.location}</span><input placeholder="60061 / Lake" value={location} onChange={e=>setLocation(e.target.value)}/></label></div></section>
    <TranslationNotice translations={translated}/><div className="list-head"><strong>{filtered.length} {t.results}</strong><span>{t.note}</span></div><section className="cards">{filtered.length ? filtered.map(r=><article className="card" key={r.id}><div className="card-top"><div><div className="chips">{r.categories.map(c=><span key={c}>{categoryLabels[ui][c] || c}</span>)}</div><h2>{r.name}</h2><p className="desc">{tr(r.description)}</p></div><a className="site-btn" href={r.website} target="_blank" rel="noopener noreferrer" aria-label={`${r.name} · ${label(ui,"Website","Sitio web","Сайт","वेबसाइट")}`}><ArrowUpRight size={20}/></a></div><div className="details"><div><MapPin size={17}/>{r.zip?<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.address)}`} target="_blank" rel="noopener noreferrer">{r.address}</a>:<span>{tr(r.address)}</span>}</div><div><Phone size={17}/><a href={`tel:${r.phone.startsWith("211")?"211":r.phone.replace(/[^\d]/g,"")}`}>{r.phone}</a></div><div><Globe2 size={17}/><span>{r.languages.map(l=>languageNames[ui][l]||l).join(" · ")}</span></div><div><Clock3 size={17}/><span>{tr(r.hours)}</span></div><div><CalendarDays size={17}/><span>{t.appointment}: {tr(r.appointment)}</span></div></div><div className="card-foot"><span>{t.verified}: {new Intl.DateTimeFormat(locale[ui]).format(new Date(r.verifiedAt+"T12:00:00"))}</span><a href={r.source} target="_blank" rel="noopener noreferrer">{t.source} ↗</a></div></article>) : <div className="empty">{t.noResults}</div>}</section>
    <footer><span>{t.intro}</span><a href="/admin">{label(ui,"Admin review","Revisión administrativa","Проверка администратором","प्रशासक समीक्षा")}</a></footer>
    {showForm && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="form-title"><button className="modal-close" onClick={()=>setShowForm(false)} aria-label={t.close}>×</button><h2 id="form-title">{t.formTitle}</h2><p>{t.formIntro}</p><form onSubmit={submit}><label>{t.name}<input name="name" required maxLength={120}/></label><label>{t.category}<select name="category" required><option value="">{t.all}</option>{categories.map(c=><option key={c} value={c}>{categoryLabels[ui][c]}</option>)}</select></label><label>{t.language}<input name="languages" placeholder={Object.values(languageNames[ui]).slice(0,2).join(", ")} required/></label><label>{t.address}<input name="address" required/></label><label>{t.phone}<input name="phone" required/></label><label>{label(ui,"Website","Sitio web","Сайт","वेबसाइट")}<input name="website" type="url" required/></label><label>{t.hours}<input name="hours" required/></label><label>{t.appointment}<select name="appointment"><option value="Call to confirm">{label(ui,"Call to confirm","Llame para confirmar","Позвоните для уточнения","पुष्टि के लिए कॉल करें")}</option><option value="Yes">{label(ui,"Yes","Sí","Да","हाँ")}</option><option value="No">{label(ui,"No","No","Нет","नहीं")}</option></select></label><label>{t.description}<input name="description" required maxLength={240}/></label><label>{t.email}<input name="contactEmail" type="email" required/></label><label>{label(ui,"Existing resource","Recurso existente","Существующий ресурс","मौजूदा संसाधन")}<select name="resourceId"><option value="">{label(ui,"New resource","Nuevo recurso","Новый ресурс","नया संसाधन")}</option>{records.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button className="primary" disabled={busy}>{t.send}</button>{status && <p role="status">{status === "sent" ? t.sent : t.error}</p>}</form></div></div>}
  </main>;
}




