"use client";

import { SiteNav, useLanguage } from "../language";

const topics = [
  { url:"https://www.uscis.gov/citizenship/learn-about-citizenship", en:["Citizenship and naturalization","Learn about the naturalization process and the steps to apply."], es:["Ciudadanía y naturalización","Conozca el proceso de naturalización y los pasos para solicitarla."], ru:["Гражданство и натурализация","Узнайте о процессе натурализации и шагах подачи заявления."] },
  { url:"https://www.uscis.gov/family", en:["Family-based immigration","Explore official information about immigration through family relationships."], es:["Inmigración por familia","Consulte información oficial sobre inmigración mediante vínculos familiares."], ru:["Иммиграция через семью","Изучите официальную информацию об иммиграции через семейные связи."] },
  { url:"https://www.uscis.gov/working-in-the-united-states", en:["Work and employment","Learn about work authorization and employment-based options."], es:["Trabajo y empleo","Conozca los permisos de trabajo y las opciones basadas en empleo."], ru:["Работа и трудоустройство","Узнайте о разрешении на работу и вариантах иммиграции через работу."] },
  { url:"https://www.uscis.gov/humanitarian", en:["Humanitarian protection","Read about asylum and other humanitarian programs from USCIS."], es:["Protección humanitaria","Lea sobre asilo y otros programas humanitarios de USCIS."], ru:["Гуманитарная защита","Прочитайте об убежище и других гуманитарных программах USCIS."] },
  { url:"https://www.justice.gov/eoir/find-legal-representation", en:["Immigration court and legal help","Find information about qualified representation in immigration proceedings."], es:["Tribunal de inmigración y ayuda legal","Encuentre información sobre representación calificada en procesos migratorios."], ru:["Иммиграционный суд и юридическая помощь","Найдите информацию о квалифицированном представительстве в иммиграционном процессе."] },
  { url:"https://www.uscis.gov/forms", en:["Forms and fees","Find current official forms, instructions and fee information."], es:["Formularios y tarifas","Encuentre formularios oficiales, instrucciones e información actual sobre tarifas."], ru:["Формы и сборы","Найдите актуальные официальные формы, инструкции и сведения о сборах."] },
] as const;
const copy = {
  English: { title:"Explore immigration pathways", intro:"Start with the topic that fits your question. These links explain possibilities; they cannot tell you which option you qualify for.", open:"Official information", help:"Talk with a qualified local organization", helpText:"Immigration rules depend on personal facts. HACES and North Suburban Legal Aid Clinic can help you ask the right questions.", hace:"Call HACES", legal:"Call legal aid", study:"Studying for citizenship?", studyText:"Use current USCIS study materials and ask College of Lake County about citizenship classes.", materials:"USCIS study materials", classes:"CLC classes", note:"This page is general information, not legal advice. Do not share private case details with the chatbot. For urgent local needs, call 211." },
  Español: { title:"Explore opciones de inmigración", intro:"Comience con el tema relacionado con su pregunta. Estos enlaces explican posibilidades; no pueden determinar para cuál reúne los requisitos.", open:"Información oficial", help:"Hable con una organización local calificada", helpText:"Las reglas migratorias dependen de su situación personal. HACES y North Suburban Legal Aid Clinic pueden ayudarle a hacer las preguntas adecuadas.", hace:"Llamar a HACES", legal:"Llamar a ayuda legal", study:"¿Estudia para la ciudadanía?", studyText:"Use los materiales actuales de USCIS y pregunte por las clases de ciudadanía en College of Lake County.", materials:"Materiales de USCIS", classes:"Clases de CLC", note:"Esta página ofrece información general, no asesoría legal. No comparta datos privados de su caso con el chatbot. Para ayuda local urgente, llame al 211." },
  Русский: { title:"Изучите иммиграционные пути", intro:"Начните с темы, которая подходит к вашему вопросу. Ссылки объясняют возможности, но не определяют, подходите ли вы под требования.", open:"Официальная информация", help:"Обратитесь в местную квалифицированную организацию", helpText:"Иммиграционные правила зависят от личных обстоятельств. HACES и North Suburban Legal Aid Clinic помогут задать нужные вопросы.", hace:"Позвонить в HACES", legal:"Позвонить юристам", study:"Готовитесь к гражданству?", studyText:"Используйте актуальные материалы USCIS и спросите о занятиях по гражданству в College of Lake County.", materials:"Материалы USCIS", classes:"Занятия CLC", note:"Это общая информация, а не юридическая консультация. Не сообщайте чат-боту личные сведения о деле. Для срочной местной помощи позвоните 211." },
};

export default function PathwaysPage() {
  const { language } = useLanguage();
  const t = copy[language];
  return <main className="more-page pathways-page"><SiteNav current="pathways" /><header className="more-heading"><div className="eyebrow">LAKE COUNTY · ILLINOIS</div><h1>{t.title}</h1><p>{t.intro}</p></header><section className="pathway-grid" aria-label={t.title}>{topics.map(topic => { const [title, description] = language === "Español" ? topic.es : language === "Русский" ? topic.ru : topic.en; return <article className="pathway-card" key={topic.url}><h2>{title}</h2><p>{description}</p><a href={topic.url} target="_blank" rel="noopener noreferrer">{t.open} ↗</a></article>; })}</section><section className="pathway-help"><h2>{t.help}</h2><p>{t.helpText}</p><div><a href="tel:8472440300">{t.hace}: 847-244-0300</a><a href="tel:8477374042">{t.legal}: 847-737-4042</a></div></section><section className="pathway-help"><h2>{t.study}</h2><p>{t.studyText}</p><div><a href="https://www.uscis.gov/citizenship/find-study-materials-and-resources" target="_blank" rel="noopener noreferrer">{t.materials} ↗</a><a href="https://www.clcillinois.edu/programs-and-classes/adult-education-and-esl" target="_blank" rel="noopener noreferrer">{t.classes} ↗</a></div></section><p className="more-note">{t.note}</p></main>;
}
